### PR TITLE
Follow basebone elements for base resource validation.

### PR DESCRIPTION
**Pull request by arscan**

### CODE REVIEW

**Comment by arscan** [comment]
Addresses https://github.com/siteadmin/inferno/issues/110

I'm a little concerned that I'm missing something, because this code is similar to profile validation (but different, since we are validating base resources against our own internal representation instead of a StructureDefintion representation). 

Should we also add valueset validation here as well?

And a reminder that this, along with our valueset validation code, will need to be added to the STU3 and upcoming R4 code.

**Comment by arscan** [comment]
It seems like the test errors that are coming up now (at least the first few -- appointment and claim) are because the fixtures we have are wrong?

**Comment by jawalonoski** [comment]
I have found that fixtures in the FHIR specification are occasionally broken, especially historically, when the validator used in publishing the specification wasn't exactly doing everything it was supposed to be doing. So, without reviewing in depth, I wouldn't be surprised if you found that here too.

**Comment by arscan** [comment]
FYI @radamson -- please be aware of this style of resource validation as an alternate to the StructureDefinition validation and merge if it looks ok to you.  Eventually we may want add external valueset validation in here too, or somehow combine them.

**Pull request merged**
