### PR TITLE
Add hooks for valueset testing

### PR DESCRIPTION
**Pull request by jmandel**
I haven't actually run this yet; just wanted to get feedback on the overall shape :-)

### CODE REVIEW

**Comment by arscan** [comment]
To make it look a little more Ruby idiomatic, you could use a code block instead of a lambda:

```ruby
FHIR::DSTU2::StructureDefinition.validates_valueset 'http://hl7.org/fhir/v3/MaritalStatus' do |coding|
   "#{coding.system}|#{coding.code}" == 'http://hl7.org/fhir/v3/MaritalStatus|S'
 end
```

But the overall approach seems good to me.

**Comment by jmandel** [comment]
Thanks  -- I updated to use blocks, and I made it pass tests. Rubocop bullied me into using a "class instance variable" instead of a class variable, which I can't say I fully liked, but it works.

**Comment by jmandel** [comment]
@arscan quick ping on this; I've put in the quick changes you requested.

**Comment by arscan** [comment]
Josh -- looks great.  I'm going to go ahead and merge it.  Though it looks like we still have to figure out warnings, and we'll also have to put this in the fhir_models gem as well.

**Pull request merged**
